
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 13 02:42:03 CLST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 9;
  public static final int COMA = 14;
  public static final int FINALIZAR = 8;
  public static final int SACAR = 5;
  public static final int ERROR = 11;
  public static final int INICIAR = 3;
  public static final int EOF = 0;
  public static final int ID = 10;
  public static final int error = 1;
  public static final int DATO = 7;
  public static final int Pc = 13;
  public static final int PARTIR = 2;
  public static final int MIRAR = 6;
  public static final int Pa = 12;
  public static final int METER = 4;
}

